[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
port = 8501
# Elimina estas l√≠neas si las tienes:
# enableCORS = false
# enableXsrfProtection = true
